name: XdToFlutter
dependencies:
  string_scanner: ^1.0.5
  ansicolor: ^1.0.2
  clippy: ^1.0.0
  
scripts:
  run: dart main.dart run
  runv: dart main.dart run -v
  runc: dart main.dart run -v -c
  run_sc: dart main.dart run -sc
  release: dartaotruntime xd_to_flutter.aot run
  build: dart2native main.dart -k aot